# Site-wide settings
# ------------------

title: Tambor – Artes Visuais
description: >-
  A Tambor é uma escola de arte em Lisboa dedicada à criatividade através da prática artística.
  Cursos, oficinas e ateliers para crianças, jovens e adultos.

url: "https://tambor.pt"

copyright: 2026 Tambor – Artes Visuais

author:
  name: Tambor
  email: tambor.time.for.art@gmail.com

# Build settings
# --------------

remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Header navigation links
# -----------------------

nav_links:
  - title: Courses
    url: /courses/
    external: false
  - title: Contact
    url: /contact/
    external: false

# Minima settings
# ---------------

minima:
  social_links:
    - title: Instagram
      icon: Instagram
      url: "https://www.instagram.com/tambor_time_for_art/"

  hide_site_feed_link: true